FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./Server.py ./
COPY ./model.joblib ./

EXPOSE 8000

CMD [ "fastapi", "run", "./Server.py" ]
